version: '3.5'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "82:82"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./conf:/etc/nginx/conf.d/
      - ./logs:/var/logs
      # - custom volume
      - /home/config/datas/front:/var/www/front
    networks:
      - wwwnet
      
  php:
    image: php:7-fpm
    container_name: nginx-php
    volumes:
      - /home/config/datas/workspace:/var/www/workspace
    command: php-fpm --allow-to-run-as-root
    privileged: true
    networks:
      - wwwnet

networks:
  wwwnet:
    driver: bridge
    name: wwwnet
