version: '3.5'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: URL
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'URL'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8003:80'
      - '2224:22'
    volumes:
      - ./datas/gitlab/config:/etc/gitlab
      - ./datas/gitlab/logs:/var/log/gitlab
      - ./datas/gitlab/datas:/var/opt/gitlab
    networks:
      - cinet

  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      
networks:
  cinet:
    name: cinet
    driver: bridge
